import { createContext, useContext, useState, useEffect, FC, ReactNode } from 'react';

type Language = 'en' | 'it';

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string, params?: Record<string, string | number>) => string;
}

const translations: Record<Language, Record<string, string>> = {
    en: {
        // Common
        admin: 'Admin',
        dashboard: 'Dashboard',
        analyze: 'Analyze',
        pricing: 'Pricing',
        inventory: 'Inventory',
        settings: 'Settings',
        accountSettings: 'Account Settings',
        manageProfileDesc: 'Manage your profile and security preferences.',
        assignedPortfolio: 'Assigned Portfolio',
        accountDetails: 'Account Details',
        emailAddress: 'Email Address',
        verifiedVia: 'Verified via HORECA Intelligence Auth.',
        security: 'Security',
        changePassword: 'Change Password',
        changePasswordDesc: 'Need to update your credentials? Click below to receive a secure password reset link at your registered email address.',
        sendResetLink: 'Send Reset Link',
        failedSendReset: 'Failed to send reset email',
        adminUserManagement: 'Admin User Management',
        manageUserPerms: 'Manage individual user permissions',
        searchUsers: 'Search users...',
        userEmail: 'User Email',
        status: 'Status',
        currentRole: 'Current Role',
        assignedBrand: 'Assigned Brand',
        actions: 'Actions',
        domainAutomationRules: 'Domain Automation Rules',
        domainAutomationDesc: 'Automatically assign brands based on email domains (e.g. @diageo.com)',
        addNewRule: 'Add New Rule',
        domainNoAt: 'Domain (no @)',
        assignBrand: 'Assign Brand',
        addAutomationRule: 'Add Automation Rule',
        autoAssigns: 'Auto-Assigns',
        securityEmailBlacklist: 'Security: Email Blacklist',
        blacklistDesc: 'Permanently block emails from signing up or accessing data',
        blockEmail: 'Block Email',
        targetEmail: 'Target Email',
        reasonInternal: 'Reason (Internal)',
        blacklistUser: 'Blacklist User',
        blacklistedEmail: 'Blacklisted Email',
        overview: 'Overview',
        brandOwner: 'Brand Owner',
        brand: 'Brand',
        drinkStrategy: 'Drink Strategy',
        insights: 'Insights',
        signOut: 'Sign Out',
        search: 'Search...',
        noData: 'No data available',
        save: 'Save',
        cancel: 'Cancel',
        applyFilters: 'Apply some filters or reload the data to start.',
        processing: 'Processing...',
        geminiAnalyzing: 'Gemini AI is analyzing data',
        marketAnalysisPlatform: 'Market Analysis Platform',
        analyticsVersion: 'Platform Analytics 2.0',
        advancedAnalytics: 'Advanced Analytics',

        // Header/Auth
        yourAccount: 'Your Account',
        timeline: 'Timeline',
        pendingVerification: 'Pending Verification',
        usually24h: 'Usually within 24h',
        signoutAndReturn: 'Sign out and return later',
        underReview: 'Application Under Review',
        thankYouReview: 'Thank you for joining HORECA Intelligence. Our administrators are currently verifying your credentials.',

        // Filter Panel
        filters: 'Filters',
        comparisonMode: 'Comparison Mode',
        none: 'None',
        yoy: 'YoY',
        qoq: 'QoQ',
        primaryYear: 'Primary Year',
        region: 'Region',
        city: 'City',
        customerType: 'Customer Type',
        venueId: 'Venue ID',
        venueName: 'Venue Name',
        productCategory: 'Product Category',
        selectAll: 'Select All',
        clearAllFilters: 'Clear All Filters',

        // Metrics
        uniqueVenues: 'Unique Venues',
        uniqueBrands: 'Unique Brands',
        totalBrandOwners: 'Total Brand Owners',
        totalBrandsListings: 'Total Brands (Listings)',
        totalCocktails: 'Total Cocktails',
        shareOfMenu: 'Share of Menu',
        presence: 'Presence',
        penetration: 'Penetration',
        avgPrice: 'Average Price',
        brandShareInCategory: 'Brand Share in Category',
        top4PositionRate: 'Top 4 Position Rate',
        cocktailPresenceRate: 'Cocktail Presence Rate',
        byVenue: 'by Venue',
        byCity: 'by City',
        justNeatSpirits: 'Just Neat Spirits',
        allBrands: 'All Brands',
        selectCocktail: 'Select a Cocktail',
        selectCocktailDesc: 'Please select a Cocktail from the main filter panel to analyze its Drink Strategy.',
        on: 'on',
        cocktailPopularity: 'Cocktail Popularity',
        venueCount: 'Venue Count',
        brandTotalPlacements: 'Brand Total Placements',
        ofTotalVenues: 'of total venues serve this cocktail',
        vsCompetitorVenues: 'vs {count} Competitor Venues',
        totalVenuesServing: 'Total venues serving this cocktail',
        avgPriceOf: 'Average price of',
        totalCombinations: 'Total brand-cocktail combinations',

        // Insights Sheet
        aiStrategicDashboard: 'AI Strategic Dashboard',
        predictiveAnalysis: 'Predictive analysis and decision support based on current filters.',
        snapshot: 'Snapshot',
        marketIntel: 'Market Intel',
        actionPlan: 'Action Plan',
        strategicQuestions: 'Strategic Questions',
        quickTargetedAnalysis: 'Quick & Targeted Analysis',
        aiResponse: 'AI Response',
        marketSentiment: 'Market Sentiment',
        reliabilityScore: 'Reliability Score',
        dataProbeSuggestion: 'Data Probe Suggestion',
        strengths: 'Strengths',
        weaknesses: 'Weaknesses',
        opportunities: 'Opportunities',
        threats: 'Threats',
        competitiveMarketMap: 'Competitive Market Map (Presence vs Opportunity)',
        competitorWhitespaceAlerts: 'Competitor & Whitespace Alerts',
        operationalPriorities: 'Operational Priorities',
        actionableRoi: 'Actionable ROI suggestions',
        aiDisclaimer: 'AI Disclaimer: These insights are generated via advanced language models by synthesizing the filtered data. Identified patterns serve as quick decision support and do not replace human analysis or direct field validation. Reliability depends on the completeness of the current dataset.',
        businessImpact: 'Business Impact',
        priority: 'Priority',
        channel: 'Channel',
        action: 'Action',
        why: 'Why',
        confidence: 'Confidence',
        reason: 'Reason',
        noBlacklistedEmailsFound: 'No blacklisted emails found.',
        vs: 'vs',
        others: 'others',
        dataFor: 'Data for',
        selectBrandOwner: 'Select a Brand Owner',
        selectBrandOwnerDesc: 'Please select a Brand Owner from the filter panel above, or click a bar on the chart below, to see a detailed performance analysis.',
        selectBrandOwnerOrBrand: 'Select a Brand or Owner',
        deepDive: 'Deep Dive',
        competitiveLandscape: 'Competitive Landscape',
        venuesFor: 'Venues for',
        exportData: 'Export Data',
        export: 'Export',
        error: 'Error',

        // Questions
        q1: 'Which are the top 3 venues with the highest growth potential?',
        q2: 'Which competitors are gaining market share?',
        q3: 'Are there untapped premiumization opportunities?',
        q4: 'What is the correlation between price and brand popularity?',
        q5: "What are the geographic 'white spots' for the selected category?",

        // SWOT
        STRENGTH: 'Strength',
        WEAKNESS: 'Weakness',
        OPPORTUNITY: 'Opportunity',
        THREAT: 'Threat',

        // Auth Modal
        signInToDashboard: 'Sign in to Dashboard',
        createYourAccount: 'Create your account',
        checkYourEmail: 'Check your email',
        updateYourPassword: 'Update your password',
        resetPassword: 'Reset Password',
        sentOtpCode: 'We just sent a 6-digit code to {email}.',
        setStrongPassword: 'Almost there! Set a strong new password to secure your account.',
        enterEmailRecovery: 'Enter your email address and we\'ll send you a recovery code.',
        enterCredentials: 'Enter your credentials below to access your workspace.',
        joinHorecaDescription: 'Join HORECA Intelligence and start analyzing trends today.',
        wrongEmailEdit: 'Wrong email? Edit address',
        newPassword: 'New Password',
        confirmNewPassword: 'Confirm New Password',
        passwordsDoNotMatch: 'Passwords do not match',
        firstName: 'First Name',
        lastName: 'Last Name',
        password: 'Password',
        forgotPassword: 'Forgot?',
        signIn: 'Sign In',
        signUp: 'Sign Up',
        backToSignIn: 'Back to sign in',
        resendVerification: 'Resend verification code',
        verifyIdentification: 'Verify identification',
        confirmNewPasswordBtn: 'Confirm new password',
        sendRecoveryCode: 'Send recovery code',
        waitCooldown: 'Please wait {seconds}s',
        otpPlaceholder: '000000',
        passwordPlaceholder: 'Min. 8 characters',
        passwordMatchPlaceholder: 'Match passwords',
        firstNamePlaceholder: 'John',
        lastNamePlaceholder: 'Doe',
        emailPlaceholder: 'name@company.com',
        dontHaveAccount: "Don't have an account?",
        alreadyHaveAccount: "Already have an account?",
        rememberPassword: "Remember your password?",
        recoveryCodeSent: "Recovery code sent! Please check your email.",
        verificationCodeSent: "Verification code sent! Please check your email.",
        invalidLogin: "User not found or incorrect password",
        tooManyRequests: "Too many requests. Please wait and try again.",
        authFailed: "Authentication failed",
        emailVerifiedSuccess: "Email verified successfully! You can now log in.",
        passwordUpdatedSuccess: "Password updated successfully! Please sign in with your new password.",

        // Update Password Modal
        createNewPassword: 'Create New Password',
        createNewPasswordDesc: 'Please enter a new password for your account. You will not be able to access the dashboard until you change it.',
        passwordUpdatedTitle: 'Password Updated!',
        redirectingToDashboard: 'Redirecting you to the dashboard...',
        saveNewPassword: 'Save New Password',
        cancelAndLogout: 'Cancel and Logout',
        passwordMinLength: 'Password must be at least {length} characters long.',

        // Pending Access
        fullAccessWait: "You will gain full access once your organization's portfolio is mapped.",

        // Recipe Analysis
        aiRecipeAnalysis: 'AI Recipe Analysis for {cocktailName}',
        analyzeRecipe: 'Analyze Recipe',
        analyzing: 'Analyzing...',
        recipeAnalysisPlaceholder: 'Click "Analyze Recipe" to get AI-powered insights on brand usage and pricing for this cocktail.',
        unavailable: 'Unavailable',
        noSentimentData: 'Analysis Pending'
    },
    it: {
        // Common
        admin: 'Amministratore',
        dashboard: 'Dashboard',
        analyze: 'Analizza',
        pricing: 'Prezzi',
        inventory: 'Inventario',
        settings: 'Impostazioni',
        accountSettings: 'Impostazioni Account',
        manageProfileDesc: 'Gestisci il tuo profilo e le preferenze di sicurezza.',
        assignedPortfolio: 'Portfolio Assegnato',
        accountDetails: 'Dettagli Account',
        emailAddress: 'Indirizzo Email',
        verifiedVia: 'Verificato tramite HORECA Intelligence Auth.',
        security: 'Sicurezza',
        changePassword: 'Cambia Password',
        changePasswordDesc: 'Hai bisogno di aggiornare le tue credenziali? Clicca qui sotto per ricevere un link di reset della password al tuo indirizzo email registrato.',
        sendResetLink: 'Invia Link di Reset',
        failedSendReset: 'Impossibile inviare l\'email di reset',
        adminUserManagement: 'Gestione Utenti Admin',
        manageUserPerms: 'Gestisci i permessi dei singoli utenti',
        searchUsers: 'Cerca utenti...',
        userEmail: 'Email Utente',
        status: 'Stato',
        currentRole: 'Ruolo Attuale',
        assignedBrand: 'Brand Assegnato',
        actions: 'Azioni',
        domainAutomationRules: 'Regole di Automazione Dominio',
        domainAutomationDesc: 'Assegna automaticamente i brand in base ai domini email (es. @diageo.com)',
        addNewRule: 'Aggiungi Nuova Regola',
        domainNoAt: 'Dominio (senza @)',
        assignBrand: 'Assegna Brand',
        addAutomationRule: 'Aggiungi Regola di Automazione',
        autoAssigns: 'Assegna Automaticamente',
        securityEmailBlacklist: 'Sicurezza: Blacklist Email',
        blacklistDesc: 'Blocca permanentemente le email dalla registrazione o dall\'accesso ai dati',
        blockEmail: 'Blocca Email',
        targetEmail: 'Email Destinatario',
        reasonInternal: 'Motivo (Interno)',
        blacklistUser: 'Metti in Blacklist l\'Utente',
        blacklistedEmail: 'Email in Blacklist',
        overview: 'Panoramica',
        brandOwner: 'Proprietario del Brand',
        brand: 'Marca',
        drinkStrategy: 'Strategia Drink',
        insights: 'Approfondimenti',
        signOut: 'Disconnetti',
        search: 'Cerca...',
        noData: 'Nessun dato disponibile',
        save: 'Salva',
        cancel: 'Annulla',
        applyFilters: 'Applica alcuni filtri o ricarica i dati per iniziare.',
        processing: 'Elaborazione...',
        geminiAnalyzing: "L'IA Gemini sta analizzando i dati",
        marketAnalysisPlatform: 'Piattaforma di Analisi di Mercato',
        analyticsVersion: 'Analisi della Piattaforma 2.0',
        advancedAnalytics: 'Analisi Avanzata',

        // Header/Auth
        yourAccount: 'Il Tuo Account',
        timeline: 'Tempistiche',
        pendingVerification: 'In attesa di verifica',
        usually24h: 'Solitamente entro 24 ore',
        signoutAndReturn: 'Esci e torna più tardi',
        underReview: 'Domanda in fase di revisione',
        thankYouReview: 'Grazie per esserti unito a HORECA Intelligence. I nostri amministratori stanno verificando le tue credenziali.',

        // Filter Panel
        filters: 'Filtri',
        comparisonMode: 'Modalità di Confronto',
        none: 'Nessuno',
        yoy: 'Anno su Anno',
        qoq: 'Trimestre su Trimestre',
        primaryYear: 'Anno Principale',
        region: 'Regione',
        city: 'Città',
        customerType: 'Tipo di Cliente',
        venueId: 'ID Locale',
        venueName: 'Nome Locale',
        productCategory: 'Categoria Prodotto',
        selectAll: 'Seleziona Tutto',
        clearAllFilters: 'Cancella Tutti i Filtri',

        // Metrics
        uniqueVenues: 'Locali Unici',
        uniqueBrands: 'Brand Unici',
        totalBrandOwners: 'Totale Proprietari Brand',
        totalBrandsListings: 'Totale Brand (Listings)',
        totalCocktails: 'Totale Cocktail',
        shareOfMenu: 'Quota di Menu',
        presence: 'Presenza',
        penetration: 'Penetrazione',
        avgPrice: 'Prezzo Medio',
        brandShareInCategory: 'Quota Brand nella Categoria',
        top4PositionRate: 'Percentuale Posizionamento Top 4',
        cocktailPresenceRate: 'Tasso Presenza nei Cocktail',
        byVenue: 'per Locale',
        byCity: 'per Città',
        justNeatSpirits: 'Solo Spirits Lisci',
        allBrands: 'Tutti i Brand',
        selectCocktail: 'Seleziona un Cocktail',
        selectCocktailDesc: 'Seleziona un Cocktail dal pannello principale dei filtri per analizzare la sua Strategia Drink.',
        on: 'su',
        cocktailPopularity: 'Popolarità Cocktail',
        venueCount: 'Numero Locali',
        brandTotalPlacements: 'Posizionamenti Totali del Brand',
        ofTotalVenues: 'dei locali totali servono questo cocktail',
        vsCompetitorVenues: 'rispetto a {count} Locali Concorrenti',
        totalVenuesServing: 'Totale locali che servono questo cocktail',
        avgPriceOf: 'Prezzo medio di',
        totalCombinations: 'Totale combinazioni brand-cocktail',

        // Insights Sheet
        aiStrategicDashboard: 'Dashboard Strategica AI',
        predictiveAnalysis: 'Analisi predittiva e supporto decisionale basati sui filtri correnti.',
        snapshot: 'Istantanea',
        marketIntel: 'Market Intel',
        actionPlan: 'Piano d\'Azione',
        strategicQuestions: 'Domande Strategiche',
        quickTargetedAnalysis: 'Analisi Rapida e Mirata',
        aiResponse: 'Risposta AI',
        marketSentiment: 'Sentimento del Mercato',
        reliabilityScore: 'Punteggio di Affidabilità',
        dataProbeSuggestion: 'Suggerimento per Sondaggio Dati',
        strengths: 'Punti di Forza',
        weaknesses: 'Punti di Debolezza',
        opportunities: 'Opportunità',
        threats: 'Minacce',
        competitiveMarketMap: 'Mappa del Mercato Competitivo (Presenza vs Opportunità)',
        competitorWhitespaceAlerts: 'Avvisi Concorrenza e Spazi Vuoti',
        operationalPriorities: 'Priorità Operative',
        actionableRoi: 'Suggerimenti ROI azionabili',
        aiDisclaimer: 'Dichiarazione di non responsabilità AI: questi approfondimenti sono generati tramite modelli linguistici avanzati sintetizzando i dati filtrati. I modelli identificati fungono da supporto decisionale rapido e non sostituiscono l\'analisi umana o la convalida diretta sul campo. L\'affidabilità dipende dalla completezza del set di dati corrente.',
        businessImpact: 'Impatto Aziendale',
        priority: 'Priorità',
        channel: 'Canale',
        action: 'Azione',
        why: 'Perché',
        confidence: 'Fiducia',
        reason: 'Motivo',
        noBlacklistedEmailsFound: 'Nessuna email in blacklist trovata.',
        vs: 'vs',
        others: 'altri',
        dataFor: 'Dati per',
        selectBrandOwner: 'Seleziona un Proprietario di Brand',
        selectBrandOwnerDesc: 'Seleziona un Proprietario di Brand dal pannello dei filtri sopra, oppure clicca su una barra del grafico qui sotto, per vedere un\'analisi dettagliata delle prestazioni.',
        selectBrandOwnerOrBrand: 'Seleziona un Brand o Proprietario',
        deepDive: 'Analisi Dettagliata',
        competitiveLandscape: 'Panorama Competitivo',
        venuesFor: 'Locali per',
        exportData: 'Esporta Dati',
        export: 'Esporta',
        error: 'Errore',

        // Questions
        q1: 'Quali sono i primi 3 locali con il più alto potenziale di crescita?',
        q2: 'Quali concorrenti stanno guadagnando quote di mercato?',
        q3: 'Esistono opportunità di premiumizzazione non sfruttate?',
        q4: 'Qual è la correlazione tra prezzo e popolarità del marchio?',
        q5: 'Quali sono i "punti bianchi" geografici per la categoria selezionata?',

        // SWOT
        STRENGTH: 'Forza',
        WEAKNESS: 'Debolezza',
        OPPORTUNITY: 'Opportunità',
        THREAT: 'Minaccia',

        // Auth Modal
        signInToDashboard: 'Accedi alla Dashboard',
        createYourAccount: 'Crea il tuo account',
        checkYourEmail: 'Controlla la tua email',
        updateYourPassword: 'Aggiorna la tua password',
        resetPassword: 'Resetta Password',
        sentOtpCode: 'Abbiamo appena inviato un codice a 6 cifre a {email}.',
        setStrongPassword: 'Quasi fatto! Imposta una nuova password sicura per proteggere il tuo account.',
        enterEmailRecovery: 'Inserisci il tuo indirizzo email e ti invieremo un codice di recupero.',
        enterCredentials: 'Inserisci le tue credenziali qui sotto per accedere al tuo spazio di lavoro.',
        joinHorecaDescription: 'Unisciti a HORECA Intelligence e inizia ad analizzare i trend oggi stesso.',
        wrongEmailEdit: 'Email errata? Modifica indirizzo',
        newPassword: 'Nuova Password',
        confirmNewPassword: 'Conferma Nuova Password',
        passwordsDoNotMatch: 'Le password non corrispondono',
        firstName: 'Nome',
        lastName: 'Cognome',
        password: 'Password',
        forgotPassword: 'Dimenticata?',
        signIn: 'Accedi',
        signUp: 'Registrati',
        backToSignIn: 'Torna all\'accesso',
        resendVerification: 'Invia di nuovo il codice di verifica',
        verifyIdentification: 'Verifica identità',
        confirmNewPasswordBtn: 'Conferma nuova password',
        sendRecoveryCode: 'Invia codice di recupero',
        waitCooldown: 'Attendi {seconds}s',
        otpPlaceholder: '000000',
        passwordPlaceholder: 'Min. 8 caratteri',
        passwordMatchPlaceholder: 'Confronta password',
        firstNamePlaceholder: 'Mario',
        lastNamePlaceholder: 'Rossi',
        emailPlaceholder: 'nome@azienda.com',
        dontHaveAccount: "Non hai un account?",
        alreadyHaveAccount: "Hai già un account?",
        rememberPassword: "Ricordi la tua password?",
        recoveryCodeSent: "Codice di recupero inviato! Controlla la tua email.",
        verificationCodeSent: "Codice di verifica inviato! Controlla la tua email.",
        invalidLogin: "Utente non trovato o password errata",
        tooManyRequests: "Troppe richieste. Per favore attendi e riprova.",
        authFailed: "Autenticazione fallita",
        emailVerifiedSuccess: "Email verificata con successo! Ora puoi accedere.",
        passwordUpdatedSuccess: "Password aggiornata con successo! Accedi con la tua nuova password.",

        // Update Password Modal
        createNewPassword: 'Crea Nuova Password',
        createNewPasswordDesc: 'Inserisci una nuova password per il tuo account. Non potrai accedere alla dashboard finché non la cambierai.',
        passwordUpdatedTitle: 'Password Aggiornata!',
        redirectingToDashboard: 'Ti stiamo reindirizzando alla dashboard...',
        saveNewPassword: 'Salva Nuova Password',
        cancelAndLogout: 'Annulla ed Esci',
        passwordMinLength: 'La password deve essere lunga almeno {length} caratteri.',

        // Pending Access
        fullAccessWait: "Otterrai l'accesso completo una volta mappato il portfolio della tua organizzazione.",

        // Recipe Analysis
        aiRecipeAnalysis: 'Analisi AI della Ricetta per {cocktailName}',
        analyzeRecipe: 'Analizza Ricetta',
        analyzing: 'Analisi in corso...',
        recipeAnalysisPlaceholder: 'Fai clic su "Analizza Ricetta" per ottenere insight basati sull\'AI sull\'utilizzo del marchio e sul prezzo per questo cocktail.'
    }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: FC<{ children: ReactNode }> = ({ children }) => {
    const language = 'en';

    const t = (key: string, params?: Record<string, string | number>) => {
        // Force English
        let text = translations['en'][key] || key;
        if (params) {
            Object.entries(params).forEach(([k, v]) => {
                text = text.replace(`{${k}}`, v.toString());
            });
        }
        return text;
    };

    return (
        <LanguageContext.Provider value={{ language: 'en', setLanguage: () => { }, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) throw new Error('useLanguage must be used within LanguageProvider');
    return context;
};
